//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SquaresEntities : DbContext
    {
        public SquaresEntities()
            : base("name=SquaresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserSquareActivity> UserSquareActivities { get; set; }
        public virtual DbSet<UserSquareActivityAction> UserSquareActivityActions { get; set; }
        public virtual DbSet<UserSquare> UserSquares { get; set; }
    }
}
