//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSquareActivityAction
    {
        public System.Guid Id { get; set; }
        public System.Guid UserSquareActivityId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public long Milliseconds { get; set; }
        public int ActivityState { get; set; }
        public string Description { get; set; }
    
        public virtual UserSquareActivity UserSquareActivity { get; set; }
    }
}
