//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSquareActivity
    {
        public System.Guid Id { get; set; }
        public System.Guid UserSquareId { get; set; }
        public System.DateTime StartUtc { get; set; }
        public long ElapsedMilliseconds { get; set; }
        public int ActivityState { get; set; }
    
        public virtual UserSquare UserSquare { get; set; }
    }
}
